//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoRentalApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        public int custID { get; set; }

        [Required(ErrorMessage = "Customer Name is a required field")]
        [StringLength(15, ErrorMessage = "Customer Name cannot exceed more than 15 characters")]
        public string Name { get; set; }

        public bool IsSubscribedToNewsletter { get; set; }
        public int membershipTypeId { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [MinAgeforMembership]  //Custom validation Attribute
        public Nullable<System.DateTime> BirthDate { get; set; }

        public virtual MembershipType MembershipType { get; set; }
    }
}
