//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoRentalApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipType
    {
        public MembershipType()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SignUpFee { get; set; }
        public Nullable<int> DurationInMonths { get; set; }
        public Nullable<int> DiscountRate { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
